name: Run UI Tests
on:
  workflow_dispatch

jobs:
  testUI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            runIde: start gradlew.bat runIdeForUiTests
          - os: macos-latest
            runIde: ./gradlew runIdeForUiTests &

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true

      - name: Run IDE
        run: ${{ matrix.runIde }}

      - name: Health Check
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://127.0.0.1:8082
          max-attempts: 15
          retry-delay: 30s

      - name: Run UI Tests
        id: ui_tests
        run: ./gradlew uiTest
        continue-on-error: true

      - name: Upload UI Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-report
          path: build/reports/tests/uiTest